baseurl = ""
languageCode = "en-us"
title = "Kvelde Legekontor"
canonifyUrls = "true"

[params]
    description = "Legene Tone C. Grimstad og Ragnhild E. Bøhm"
    custom_css = ["css/local.css"]

[[params.social]]
    title = "33 11 34 70"
    icon = "phone"
    url = "tel:33113470"
[[params.social]]
    title = "e-post"
    icon = "envelope-o"
    url = "mailto:bushbama@whitehouse.gov"
[[params.social]]
    title = "facebook"
    icon = "facebook"
    url = "https://twitter.com/SBootstrap"
#[[params.social]]
#    title = "github"
#    icon = "github"
#    url = "https://github.com/IronSummitMedia/startbootstrap"
#[[params.social]]
#    title = "linkedin"
#    icon = "linkedin"
#    url = "http://linkedin.com/in/yourusername"
